name: monopoly
description: Simple accounting application for Monopoly like games.
publish_to: 'none'
version: 0.0.1+1

environment:
  sdk: '>=3.0.0-229.0.dev <4.0.0'
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
